# Generated by Django 6.0.3 on 2026-03-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminals', '0001_initial'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('method_used', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cold', 'Cold Case')], default='Open', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimes.crime')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.criminal')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='criminals_involved',
            field=models.ManyToManyField(related_name='crimes_involved', through='crimes.CrimeInvolvement', to='criminals.criminal'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='crimes.crime')),
            ],
        ),
        migrations.CreateModel(
            name='Investigates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_worked', models.DateField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimes.crime')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='officers_investigating',
            field=models.ManyToManyField(related_name='crimes_investigated', through='crimes.Investigates', to='officers.officer'),
        ),
        migrations.CreateModel(
            name='CrimeVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimes.crime')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimes.victim')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='victims_involved',
            field=models.ManyToManyField(related_name='crimes_involved', through='crimes.CrimeVictim', to='crimes.victim'),
        ),
        migrations.CreateModel(
            name='VictimPhone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='crimes.victim')),
            ],
        ),
    ]
