# Generated by Django 6.0.3 on 2026-03-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('court_date', models.DateField()),
                ('judge_name', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_dates', to='cases.case')),
            ],
        ),
    ]
