# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("court", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE `court_court` "
                "ADD COLUMN `verdict` VARCHAR(20) NOT NULL DEFAULT 'PENDING', "
                "ADD COLUMN `verdict_date` DATETIME(6) NULL, "
                "ADD COLUMN `sentence_type` VARCHAR(30) NULL, "
                "ADD COLUMN `sentence_length_months` INT NULL, "
                "ADD COLUMN `fine_amount` DECIMAL(12, 2) NULL, "
                "ADD COLUMN `verdict_notes` LONGTEXT NULL",
            ],
            reverse_sql=[
                "ALTER TABLE `court_court` "
                "DROP COLUMN `verdict_notes`, "
                "DROP COLUMN `fine_amount`, "
                "DROP COLUMN `sentence_length_months`, "
                "DROP COLUMN `sentence_type`, "
                "DROP COLUMN `verdict_date`, "
                "DROP COLUMN `verdict`",
            ],
            state_operations=[
                migrations.AddField(
                    model_name="court",
                    name="verdict",
                    field=models.CharField(
                        choices=[
                            ("GUILTY", "Guilty"),
                            ("NOT_GUILTY", "Not Guilty"),
                            ("DISMISSED", "Dismissed"),
                            ("PLEA_DEAL", "Plea Deal"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="court",
                    name="verdict_date",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="court",
                    name="sentence_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("PRISON", "Prison"),
                            ("PROBATION", "Probation"),
                            ("FINE", "Fine"),
                            ("COMMUNITY_SERVICE", "Community Service"),
                            ("NONE", "None"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="court",
                    name="sentence_length_months",
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="court",
                    name="fine_amount",
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                migrations.AddField(
                    model_name="court",
                    name="verdict_notes",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]

