# Generated by Django 6.0.3 on 2026-03-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('warrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warrants', to='criminals.criminal')),
            ],
        ),
    ]
