# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0001_initial"),
        ("crimes", "0002_crime_city_crime_latitude_crime_longitude"),
        ("criminals", "0002_criminal_is_repeat_offender_and_more"),
        ("cases", "0002_case_opened_date"),
        ("warrants", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "CREATE TABLE `officers_assignment` ("
                        "`assignment_id` int AUTO_INCREMENT NOT NULL PRIMARY KEY, "
                        "`task_type` varchar(50) NOT NULL, "
                        "`status` varchar(20) NOT NULL DEFAULT 'ASSIGNED', "
                        "`priority` int NOT NULL DEFAULT 3, "
                        "`assigned_at` datetime(6) NOT NULL, "
                        "`due_at` datetime(6) NULL, "
                        "`completed_at` datetime(6) NULL, "
                        "`notes` longtext NULL, "
                        "`officer_id` int NOT NULL, "
                        "`crime_id` int NULL, "
                        "`criminal_id` int NULL, "
                        "`case_id` int NULL, "
                        "`warrant_id` int NULL, "
                        "CONSTRAINT `officers_assignment_officer_id_fk` FOREIGN KEY (`officer_id`) REFERENCES `officers_officer` (`officer_id`) ON DELETE CASCADE, "
                        "CONSTRAINT `officers_assignment_crime_id_fk` FOREIGN KEY (`crime_id`) REFERENCES `crimes_crime` (`crime_id`) ON DELETE SET NULL, "
                        "CONSTRAINT `officers_assignment_criminal_id_fk` FOREIGN KEY (`criminal_id`) REFERENCES `criminals_criminal` (`criminal_id`) ON DELETE SET NULL, "
                        "CONSTRAINT `officers_assignment_case_id_fk` FOREIGN KEY (`case_id`) REFERENCES `cases_case` (`case_id`) ON DELETE SET NULL, "
                        "CONSTRAINT `officers_assignment_warrant_id_fk` FOREIGN KEY (`warrant_id`) REFERENCES `warrants_warrant` (`warrant_id`) ON DELETE SET NULL"
                        ")",
                    ],
                    reverse_sql=[
                        "DROP TABLE `officers_assignment`",
                    ],
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Assignment",
                    fields=[
                        ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                        ("task_type", models.CharField(max_length=50)),
                        ("status", models.CharField(default="ASSIGNED", max_length=20)),
                        ("priority", models.IntegerField(default=3)),
                        ("assigned_at", models.DateTimeField(auto_now_add=True)),
                        ("due_at", models.DateTimeField(blank=True, null=True)),
                        ("completed_at", models.DateTimeField(blank=True, null=True)),
                        ("notes", models.TextField(blank=True, null=True)),
                        (
                            "case",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="assignments",
                                to="cases.case",
                            ),
                        ),
                        (
                            "crime",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="assignments",
                                to="crimes.crime",
                            ),
                        ),
                        (
                            "criminal",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="assignments",
                                to="criminals.criminal",
                            ),
                        ),
                        (
                            "officer",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="assignments",
                                to="officers.officer",
                            ),
                        ),
                        (
                            "warrant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="assignments",
                                to="warrants.warrant",
                            ),
                        ),
                    ],
                ),
            ],
        ),
    ]

