# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0002_assignment_model"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE `officers_assignment` "
                "ADD COLUMN `sector_name` VARCHAR(100) NULL AFTER `priority`"
            ],
            reverse_sql=[
                "ALTER TABLE `officers_assignment` DROP COLUMN `sector_name`"
            ],
            state_operations=[
                migrations.AddField(
                    model_name="assignment",
                    name="sector_name",
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
