# Generated by Django 6.0.3 on 2026-03-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Finished', 'Finished')], default='Open', max_length=50)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='crimes.crime')),
            ],
        ),
    ]
