# Generated by Django 6.0.3 on 2026-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
