# Generated by Django 6.0.3 on 2026-03-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('physical_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('interrogation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations_involved', to='criminals.criminal')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to='officers.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('nickname_id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=100)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='criminals.criminal')),
            ],
        ),
    ]
