# Generated by Django 6.0.3 on 2026-04-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='is_repeat_offender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
