# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criminals", "0002_criminal_is_repeat_offender_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE `criminals_criminal` "
                "ADD COLUMN `current_status` VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN', "
                "ADD COLUMN `jail_number` VARCHAR(50) NULL, "
                "ADD COLUMN `jail_name` VARCHAR(150) NULL, "
                "ADD COLUMN `status_updated_at` DATETIME(6) NULL",
            ],
            reverse_sql=[
                "ALTER TABLE `criminals_criminal` "
                "DROP COLUMN `status_updated_at`, "
                "DROP COLUMN `jail_name`, "
                "DROP COLUMN `jail_number`, "
                "DROP COLUMN `current_status`",
            ],
            state_operations=[
                migrations.AddField(
                    model_name="criminal",
                    name="current_status",
                    field=models.CharField(
                        choices=[
                            ("IN_JAIL", "In Jail"),
                            ("RELEASED", "Released"),
                            ("WANTED", "Wanted"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="criminal",
                    name="jail_number",
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name="criminal",
                    name="jail_name",
                    field=models.CharField(blank=True, max_length=150, null=True),
                ),
                migrations.AddField(
                    model_name="criminal",
                    name="status_updated_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]

