# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criminals", "0003_criminal_current_status_and_jail"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE `criminals_criminal` "
                "ADD COLUMN `bounty_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00"
            ],
            reverse_sql=[
                "ALTER TABLE `criminals_criminal` DROP COLUMN `bounty_amount`"
            ],
            state_operations=[
                migrations.AddField(
                    model_name="criminal",
                    name="bounty_amount",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
    ]
