# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criminals", "0004_criminal_bounty_amount"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE `criminals_criminal` "
                "ADD COLUMN `sector_name` VARCHAR(100) NULL"
            ],
            reverse_sql=[
                "ALTER TABLE `criminals_criminal` DROP COLUMN `sector_name`"
            ],
            state_operations=[
                migrations.AddField(
                    model_name="criminal",
                    name="sector_name",
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
